services:
    filebrowser:
        container_name: filebrowser
        restart: unless-stopped
        volumes:
            - /home/holmie:/srv/home
            - /mnt/4tb:/srv/mounted
            - ./database:/database
            - ./settings.json:/config/settings.json
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 8060:80
        command: ["-c", "/config/settings.json"] # required, see https://github.com/filebrowser/filebrowser/issues/1898
        image: filebrowser/filebrowser:latest
# make all folders and files before running this.
