services:
    filebrowser:
        container_name: filebrowser
        env_file:
           - ../env
        restart: unless-stopped
        volumes:
            - /home/holmie:/srv/home
            - /mnt/hdd:/srv/mounted
            - ./database:/database
            - ./settings.json:/config/settings.json
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - 8060:80
        command: ["-c", "/config/settings.json"] # required, see https://github.com/filebrowser/filebrowser/issues/1898
        image: filebrowser/filebrowser:latest
