services:
    ollama:
        volumes:
            - ./ollama:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
        restart: unless-stopped
        image: ollama/ollama
    open-webui:
        ports:
            - 3000:8080
        volumes:
            - ./open-webui:/app/backend/data
        container_name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        restart: unless-stopped