services:
    navidrome:
        container_name: navidrome
        restart: on-failure
        user: 1000:1000
        volumes:
            - /mnt/hdd/music:/music:ro
            - ./data:/data
        ports:
            - 4533:4533
        environment:
            - ND_LOGLEVEL=info
            - ND_SCANSCHEDULE=100m
            - ND_ENABLEINSIGHTSCOLLECTOR=false # turn off telemetry
        image: deluan/navidrome:latest
