services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - FTLCONF_webserver_api_password=password
      - FTLCONF_dns_upstreams=9.9.9.9;1.1.1.1
    volumes:
      - ${CONFIG_STORAGE_LOCATION}/pihole/etc-pihole:/etc/pihole
      - ${CONFIG_STORAGE_LOCATION}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - ${pihole_server_ip}:53:53/tcp
      - ${pihole_server_ip}:53:53/udp
      - "5353:80/tcp"
    restart: unless-stopped
