services:
    nextcloud:
        container_name: nextcloud
        ports:
            - 8086:80
        restart: unless-stopped
        volumes:
            - ./nextcloud/html:/var/www/html
            - ./nextcloud/apps:/var/www/html/custom_apps
            - ./nextcloud/config:/var/www/html/config
            - ./nextcloud/data:/var/www/html/data
        image: nextcloud:latest
# the nextcloud folder wants to be in the group www-data
# sudo chown -R www-data:www-data nextcloud/
# but cd into /home/skynet/config first (assuming nextcloud the folder is inside config
