services:
    netalertx:
        network_mode: host
        volumes:
            - ./config:/app/config
            - ./db:/app/db
            - /home/pi3/pihole/etc-pihole/pihole-FTL.db:/etc/pihole/pihole-FTL.db:ro
        environment:
            - TZ=America/New_York
            - PORT=20211
        container_name: netalertx
        restart: unless-stopped
        image: jokobsk/netalertx:latest
